feat(metro-plugin-duplicates-checker): support metro-serializer plugins (#120)
`metro-plugin-duplicates-checker` now supports `metro-serializer` plugin
infrastructure. Example usage:

```js
const { makeMetroConfig } = require("@rnx-kit/metro-config");
const {
  DuplicateDependencies,
} = require("@rnx-kit/metro-plugin-duplicates-checker");
const { MetroSerializer } = require("@rnx-kit/metro-serializer");

module.exports = makeMetroConfig({
  projectRoot: __dirname,
  serializer: {
    customSerializer: MetroSerializer([DuplicateDependencies()]),
  },
});
```

Example output:

```
fbjs (found 2 copies)
  1.0.0 /~/rnx-kit/node_modules/fbjs
  3.0.0 /~/rnx-kit/packages/test-app/node_modules/fbjs
error Duplicates found. Run CLI with --verbose flag for more details.
Error: Duplicates found
    at /~/rnx-kit/packages/metro-plugin-duplicates-checker/lib/index.js:37:23
    at /~/rnx-kit/packages/metro-serializer/lib/index.js:42:37
    at Array.forEach (<anonymous>)
    at Object.customSerializer (/~/rnx-kit/packages/metro-serializer/lib/index.js:42:17)
    at /~/rnx-kit/node_modules/metro/src/Server.js:562:50
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/~/rnx-kit/node_modules/metro/src/Server.js:99:24)
    at _next (/~/rnx-kit/node_modules/metro/src/Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```