feat: cyclic dependencies plugin for Metro (#116)
Metro plugin for detecting cyclic dependencies. To use it, add it to
`metro-serializer` introduced in #115:

```js
const { makeMetroConfig } = require("@rnx-kit/metro-config");
const {
  CyclicDependencies,
} = require("@rnx-kit/metro-plugin-cyclic-dependencies-detector");
const { MetroSerializer } = require("@rnx-kit/metro-serializer");

module.exports = makeMetroConfig({
  projectRoot: __dirname,
  serializer: {
    customSerializer: MetroSerializer([
      CyclicDependencies(),
    ]),
  },
});
```

Example output:

```
@rnx-kit/test-app/lib/src/App.js
└── @rnx-kit/test-app/lib/src/cyclicExample.js
    └── @rnx-kit/test-app/lib/src/App.js
        └── @rnx-kit/test-app/lib/src/index.js

error Require cycles detected. Run CLI with --verbose flag for more details.
Error: Require cycles detected
    at Object.detectCycles (/~/rnx-kit/packages/metro-plugin-cyclic-dependencies-detector/lib/detectCycles.js:82:15)
    at /~/rnx-kit/packages/metro-plugin-cyclic-dependencies-detector/lib/index.js:7:24
    at /~/rnx-kit/packages/metro-serializer/lib/index.js:42:37
    at Array.forEach (<anonymous>)
    at Object.customSerializer (/~/rnx-kit/packages/metro-serializer/lib/index.js:42:17)
    at /~/rnx-kit/node_modules/metro/src/Server.js:562:50
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/~/rnx-kit/node_modules/metro/src/Server.js:99:24)
    at _next (/~/rnx-kit/node_modules/metro/src/Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```